### ISSUE TITLE
java.io.FileNotFoundException: open failed: EROFS (Read-only file system)

### ISSUE THREAD

**Issue by ape-report** [SimpleMobileTools/Simple-File-Manager#206]
When compressing a file or folder in a system folder,
the app crashes due to permission issues.

```
// java.io.FileNotFoundException: /4.zip: open failed: EROFS (Read-only file system)
//  at libcore.io.IoBridge.open(IoBridge.java:452)
//  at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
//  at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
//  at com.simplemobiletools.commons.extensions.ActivityKt.getFileOutputStreamSync(SourceFile:594)
//  at com.simplemobiletools.commons.extensions.ActivityKt.getFileOutputStreamSync$default(SourceFile:580)
//  at com.simplemobiletools.filemanager.adapters.ItemsAdapter.zipPaths(SourceFile:293)
//  at com.simplemobiletools.filemanager.adapters.ItemsAdapter.access$zipPaths(SourceFile:40)
//  at com.simplemobiletools.filemanager.adapters.ItemsAdapter$compressSelection$1$1$1.run(SourceFile:223)
//  at java.lang.Thread.run(Thread.java:818)
// Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
//  at libcore.io.Posix.open(Native Method)
//  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
//  at libcore.io.IoBridge.open(IoBridge.java:438)
//  ... 8 more
```

**Comment by tibbi** [comment]
error will be caught and displayed in the next version, proper root file handling is a more generic issue
