### ISSUE TITLE
EACCES (Permission denied) while opening a file in another application

### ISSUE THREAD

**Issue by proninyaroslav** [SimpleMobileTools/Simple-File-Manager#395]
Hi. I received this error from one of the users of my app (Android 8.1.0). He used your file manager to open and read the torrent file:

```
content://com.simplemobiletools.filemanager.pro.provider/external_files/dev/block/platform/soc/7824900.sdhci/by-name/encrypt: open failed: EACCES (Permission denied)
	at org.proninyaroslav.libretorrent.ui.addtorrent.AddTorrentViewModel$TorrentDecodeTask.readTorrentFile(AddTorrentViewModel.java:294)
	at org.proninyaroslav.libretorrent.ui.addtorrent.AddTorrentViewModel$TorrentDecodeTask.doInBackground(AddTorrentViewModel.java:269)
	at org.proninyaroslav.libretorrent.ui.addtorrent.AddTorrentViewModel$TorrentDecodeTask.doInBackground(AddTorrentViewModel.java:197)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```
I tried the same thing and downloaded your app from F-Droid, but I didn't get such an error.

**Comment by tibbi** [comment]
please specify how can I reproduce the issue. Also, what File manager version does it happen to?

**Comment by proninyaroslav** [comment]
I have little information. I think that your app is not a `Storage Access Framework` provider, so the user simply opened a torrent file in the file manager window.

**Comment by tibbi** [comment]
it is, should work just fine. Maybe he uses some ancient app version.

**Comment by proninyaroslav** [comment]
I will supplement issue if I can get more information from him. Thank you.

**Comment by tibbi** [comment]
ok, reopen if you have more info and the user is using the latest Pro version, currently 6.6.1.
